### ISSUE TITLE
Add touchstart event to bind list

### ISSUE THREAD

**Issue by sirideain** [Eisa01/FreshRSS---Auto-Refresh-Extension#1]
The page refreshes while reading on a phone now as touch events aren't detected.

**Comment by Eisa01** [comment]
Thanks for considering mobile devices. And for adding the compatibility in your pull request.

I will mark the issue as closed and merge your pull requests since you have solved the issues.
Thank you ^ ^

Fixed due to [pull request #2](https://github.com/Eisa01/FreshRSS---Auto-Refresh-Extension/pull/2) by @sirideain
